### ISSUE TITLE
Missing case for FILM_K in Screen_EPD_EXT3::begin

### ISSUE THREAD

**Issue by SzGaa** [rei-vilo/PDLS_EXT3_Basic_Global#17]
### Describe the problem

Simple example programs fail for FILM_K type displays.

### To reproduce

Use latest 'PDLS_EXT3_Basic_Global' library (version 8.0.1).
Try to execute any example programs with panel with FILM_K type. (e.g. eScreen_EPD_266_KS_0C)

The software compiles, but fails during runtime:
```
begin... 
hV * Screen 266-KS-0C is not supported
```

### Expected behavior

The examples works well for all FILM_K type displays as 'Basic Global Library' meant to support it.

### IDE or SDK name and version

Arduino v2.3.2

### PDLS variant

PDLS_EXT3_Basic_Global

### PDLS version

8.0.1

### MCU board

ESP32S3 Dev Module (custom pinout)

### Extension board

EXT3-1

### EPD panel reference

E2266KS0C1

### Additional context

After adding the missed 'case' entry the example programs are working as expected!

```
--- a/src/Screen_EPD_EXT3.cpp
+++ b/src/Screen_EPD_EXT3.cpp
@@ -1009,6 +1009,7 @@ void Screen_EPD_EXT3::begin()
     switch (u_codeFilm)
     {
         case FILM_C: // Standard
+        case FILM_K:
         case FILM_H: // BW, Freezer
         case FILM_E: // BWR, deprecated
         case FILM_F: // BWR, deprecated
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/rei-vilo/PDLS_EXT3_Basic_Global/issues?q=)
- [X] My report contains all necessary details

**Comment by rei-vilo** [comment]
The KS film features wide temperature with embedded fast update.

The corresponding library is the [PDLS_EXT3_Basic_Fast](https://github.com/PervasiveDisplays/PDLS_EXT3_Basic_Fast), as described at [Select the library](https://pdls.pervasivedisplays.com/userguide/Volume3/Chapter3/Section3/).

The reason is, PDLS follows the applications notes more closely. As a result, PDLS now reads the OTP memory from the screen to ensure optimal image quality. Screens with KS film feature OTP memory, previous generation screens with CS film do not.
